In [63]:
from numba import jit
import cv2
import numpy as np
from IPython.display import clear_output


In [64]:
img = cv2.imread('oregon1.jpeg', 1)
img2 = cv2.imread('oregon2.jpeg', 1)

imgarr = np.array([img])

imgarr = np.append( imgarr, [img2], axis=0 )

In [65]:

def getBrightness(px):
    return(0.299*px[0] + 0.587*px[1] + 0.114*px[2])

In [66]:

def orderPixels(pxarr):

    test_b = np.apply_along_axis(getBrightness, 1, pxarr)
    return pxarr[ np.argsort(test_b) ]

In [67]:

def getPixelArray(imgArray, xpos, ypos):
    temp = np.array([imgArray[0,xpos,ypos]])
    
    for x in range(1, imgArray.shape[0]):
        temp = np.append( temp, [imgArray[x, xpos, ypos]], axis=0 )
    
    return temp

In [68]:

def savePixelArray(imgArray, pxArray, xpos, ypos):
    for t in range(0, imgArray.shape[0]):
        imgArray[t,xpos,ypos] = pxArray[t]
        
    return imgArray

In [69]:
#print img2[0,0]
#print imgarr[1,10,10]
#print imgarr[0,10,10]
#print imgarr[0].shape[1]
#getPixelArray(imgarr, 30, 30)
s = 100
print(getPixelArray(imgarr, s, s))
print(orderPixels(getPixelArray(imgarr,s,s)))
#print "something" + str(14) + "other"
#if (3000 % 101 == 0):
 #   print "true statement"

[[185 191 190]
 [157 159 159]]
[[157 159 159]
 [185 191 190]]


In [70]:
#test = np.array([img[0,0]]);
 
#for x in range(1, 10):
#    test = np.append( test, [img[x*100,x*100]],  axis=0 )

for x in range(0, imgarr[0].shape[0]):
    if (x % 10 == 0):
        clear_output(wait=1)
        print(str(x*10/imgarr[0].shape[0]) + "% done")
    for y in range(0, imgarr[0].shape[1]):
        imgarr = savePixelArray(imgarr, orderPixels(getPixelArray(imgarr,x,y)), x, y)
        a
        

for x in range(0, imgarr.shape[0]):
    cv2.imwrite('out'+ str(x)+'.png',imgarr[x])

9.948979591836734% done
